{% set name = "PDAL" %}
{% set version = "1.5.0" %}
{% set sha256 = "b5ce59a87a9cb8b4c8cd2b63e92b559b0bae16e3adf7ab9b5f85d4c9f11d185e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-1.5.tar.gz
  url: https://github.com/PDAL/PDAL/archive/1.5.tar.gz
  sha256: {{ sha256 }}

build:
  number: 6
  skip: True  # [py36 and linux]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - cmake
    - cython
    - numpy x.x
    - gdal
    - geotiff
    - laszip
    - lazperf [linux]
    - libpq
    - libxml2
    - libiconv
    - packaging
    - pcl
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

  run:
    - python
    - cython
    - numpy x.x
    - gdal
    - geotiff
    - laszip
    - lazperf [linux]
    - libpq
    - libxml2
    - libiconv
    - pcl
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

test:
  imports:
    - pdal
  commands:
    - pdal --version
    - pdal --drivers
    - pdal --options filter.programmable
    - conda inspect linkages {{ name|lower }}

about:
  home: https://www.pdal.io/
  license: BSD
  summary: 'Point cloud data processing'

extra:
  recipe-maintainers:
    - mathieu1
