{% set name = "PDAL" %}
{% set version = "1.6.0" %}
{% set sha256 = "66baf8510225b34ee24021731758251cd70657dd578c210ae86c78d158f283eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-1.6.tar.gz
  url: https://github.com/PDAL/PDAL/archive/1.6.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py36 and linux]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - cmake
    - cython
    - numpy x.x
    - gdal 2.2.2
    - geotiff
    - laszip
    - lazperf [linux]
    - postgresql
    - libxml2
    - libiconv
    - packaging
    - pcl
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

  run:
    - python
    - cython
    - numpy x.x
    - gdal 2.2.2
    - geotiff
    - laszip
    - lazperf [linux]
    - postgresql
    - libxml2
    - libiconv
    - pcl
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

test:
  imports:
    - pdal
  commands:
    - pdal --version
    - pdal --drivers
    - pdal --options filter.programmable
#    - conda inspect linkages {{ name|lower }}

about:
  home: https://www.pdal.io/
  license: BSD
  summary: 'Point cloud data processing'

extra:
  recipe-maintainers:
    - mathieu1
