{% set name = "lazperf" %}
{% set version = "1.1.0" %}
{% set sha256 = "b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hobu/laz-perf/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py36 and linux]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - cython
    - cmake
    - numpy >=1.11
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

  run:
    - python
    - cython
    - numpy >=1.11
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

test:
  imports:
    - lazperf

about:
  home: https://github.com/hobu/laz-perf/
  license: LGPL
  summary: 'Point cloud data compression'

extra:
  recipe-maintainers:
    - mathieu1
